// components/vendor/PrintLayout.tsx
import React from "react";

interface PrintLayoutProps {
  period: "week" | "month" | "year";
  stats: {
    revenueData: number[];
    bookings: number;
    users: number;
    vendors: number;
  };
  getChartLabels: (period: string) => string[];
}

const PrintLayout: React.FC<PrintLayoutProps> = ({
  period,
  stats,
  getChartLabels,
}) => {
  const totalRevenue = stats.revenueData.reduce((a, b) => a + b, 0);

  return (
    <div className="print-layout">
      {/* Add print styles */}
      <style>
        {`
          @media print {
            @page {
              margin: 1cm;
              size: A4 portrait;
            }

            body {
              -webkit-print-color-adjust: exact;
              background: white !important;
            }

            /* Hide non-essential elements */
            header, footer, button, .no-print {
              display: none !important;
            }

            /* Print-specific header */
            .print-header {
              display: block !important;
              text-align: center;
              border-bottom: 2px solid #000;
              padding-bottom: 1rem;
              margin-bottom: 2rem;
            }

            /* Stats summary */
            .stats-summary {
              display: grid;
              grid-template-columns: repeat(2, 1fr);
              gap: 1rem;
              margin-bottom: 2rem;
            }

            .stat-item {
              display: flex;
              justify-content: space-between;
              padding: 0.5rem;
              border: 1px solid #ddd;
              border-radius: 4px;
            }

            /* Data tables */
            .print-table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 1rem;
            }

            .print-table th,
            .print-table td {
              padding: 0.75rem;
              border: 1px solid #ddd;
              text-align: left;
            }

            .print-table th {
              background: #f7f7f7;
            }

            /* Print footer */
            .print-footer {
              text-align: center;
              margin-top: 2rem;
              padding-top: 1rem;
              border-top: 1px solid #ddd;
              font-size: 0.875rem;
              color: #666;
            }
          }
        `}
      </style>

      {/* Print Header */}
      <div className="print-header">
        <h1 className="text-2xl font-bold">Viao Revenue Report</h1>
        <p className="text-gray-600">
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </p>
      </div>

      {/* Stats Summary */}
      <div className="stats-summary">
        <div className="stat-item">
          <span>Total Revenue</span>
          <span>₹{totalRevenue.toLocaleString()}</span>
        </div>
        <div className="stat-item">
          <span>Total Bookings</span>
          <span>{stats.bookings}</span>
        </div>
        <div className="stat-item">
          <span>Total Users</span>
          <span>{stats.users}</span>
        </div>
        <div className="stat-item">
          <span>Total Vendors</span>
          <span>{stats.vendors}</span>
        </div>
      </div>

      {/* Revenue Table */}
      <table className="print-table">
        <thead>
          <tr>
            <th>Period</th>
            <th>Revenue</th>
            <th>% of Total</th>
          </tr>
        </thead>
        <tbody>
          {stats.revenueData.map((value, index) => (
            <tr key={index}>
              <td>{getChartLabels(period)[index]}</td>
              <td>₹{value.toLocaleString()}</td>
              <td>{value !== 0 ? ((value / totalRevenue) * 100).toFixed(1) : 0}%</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Print Footer */}
      <div className="print-footer">
        <p>viaoind@gmail.com</p>
        <p>Generated by Viao Analytics Platform</p>
      </div>
    </div>
  );
};

export default PrintLayout;