export const VENDOR = {
    VENDOR: "/vendor",
    LOGIN: "/vendor/login",
    SIGNUP: "/vendor/signup",
    VERIFY: "/vendor/verify",
    FORGOT_PWD: "/vendor/forgot-password",
    RESET_PWD: "/vendor/reset-password",
    
    CHAT: "/vendor/chat",
    DASHBOARD: "/vendor/dashboard",
    VIEW_PROFILE: "/vendor/view-profile",
    EDIT_PROFILE: "/vendor/edit-profile",
    CHANGE_PWD: "/vendor/change-password",
    VIEW_POSTS: "/vendor/view-posts",
    ADD_POSTS: "/vendor/add-post",
    SERVICES: "/vendor/services",
    BOOKING_HISTORY: "/vendor/booking-history",
    ADD_DATE: "/vendor/add-date",
    REVIEWS: "/vendor/reviews",
    NOTIFICATIONS: "/vendor/notifications",
    VIEW_BOOKING: "/vendor/view-booking",
  };  